---
version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo Hello, World!
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say bye
          command: echo bye, People!
workflows:
  workflow1:
    jobs:
      - say-hello
      - say-bye
  workflow2:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
  workflow3:
    jobs:
      - approval:
          type: approval
      - say-hello:
          requires:
            - approval    
      - say-bye:
          requires:
            - say-hello

  program:
    triggers:
      - schedule:
            cron: "49 17 * * *"
            filters:
              branches:
                only:
                  main

    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
