version: 2.1

jobs:
  say-hello:
      parameters:
        name:
          type: string
          default: Josmir
      docker:
        - image: cimg/base:stable
      steps:
      - run:
          name: Say hello parameter
          command: echo Hello, << parameters.name >>

workflows:
  workflow1:
    jobs:
      - say-hello
  workflow2:
    jobs:
      - say-hello:
          name: Genesis
