version: 2.1

jobs:
  say-hello:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello