version: 2.1

commands:
  dime-hora-espera:
    steps:
      - run:
          command: date && sleep 10
jobs:
  say-hello:
    docker:
      - image: ubuntu:latest
    steps:
      - dime-hora-espera
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - dime-hora-espera
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - dime-hora-espera
      - run:
          name: "Say hello"
          command: "echo Hello, World!"  
      - dime-hora-espera

workflows:
  say-workflow:
    jobs:
      - say-hello
      - say-bye