version: 2.1

parameters:
  nanme:
    type: string
    default: Josmir

jobs:
  say-hello:
      docker:
        - image: cimg/base:stable
      steps:
      - run:
          name: Say hello parameter
          command: echo Hello, << pipeline.parameters.name >>

workflows:
  workflow1:
      jobs:
        - say-hello

