version: 2.1

jobs:
  say-hello:
      parameters: #este es un parametro a nivel de jobs
        nombre:
          type: string
          default: Josmir
      docker:
        - image: cimg/base:stable
      steps:
      - run:
          name: Say hello parameter
          command: echo Hello, << parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - say-hello
  workflow2:
    jobs:
      - say-hello:
          nombre: Genesis
