version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echoa instalando aws cli

jobs:
  install-dependencies:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout: #el checkout me permite bajar el codigo del repositorio al agente
          path: micodigo/ #el path, me permite indicarle una ruta donde quiere que baje el codigo
      - run: 
          command: find
      - install-aws-cli

workflows:
  workflow1:
    jobs:
      - install-dependencies
